version: "3"
services:
  web:
    profiles:
      - dev
      - testnet
    build:
      context: ./
      dockerfile: ./web/Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - "./web:/web"
      - "/web/node_modules"
    environment:
      - CHAIN_ENV=${CHAIN_ENV}
      - FAUCET_ADDRESS=${FAUCET_ADDRESS}
      - ACCESS_API_WEB=${ACCESS_API_WEB}
      - WALLET_DISCOVERY=${WALLET_DISCOVERY}
      - FUNGIBLE_TOKEN_ADDRESS=${FUNGIBLE_TOKEN_ADDRESS}
      - NON_FUNGIBLE_TOKEN_ADDRESS=${NON_FUNGIBLE_TOKEN_ADDRESS}
      - FUSD_TOKEN_ADDRESS=${FUSD_TOKEN_ADDRESS}
      - API_URL=${API_URL}
      - FLOW_ADDRESS=${FLOW_ADDRESS}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
  api:
    profiles:
      - dev
      - testnet
      - api
    build:
      context: ./
      dockerfile: ./api/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./api:/api"
      - "/api/node_modules"
    links:
      - "db:database"
    environment:
      - MINTER_ADDRESS=${FLOW_ADDRESS}
      - MINTER_PRIVATE_KEY=${FLOW_PRIVATE_KEY}
      - MINTER_ACCOUNT_KEY_INDEX=0
      - FUNGIBLE_TOKEN_ADDRESS=${FUNGIBLE_TOKEN_ADDRESS}
      - NON_FUNGIBLE_TOKEN_ADDRESS=${NON_FUNGIBLE_TOKEN_ADDRESS}
      - FUSD_TOKEN_ADDRESS=${FUSD_TOKEN_ADDRESS}
      - FLOW_ACCESS_API_URL=${ACCESS_API_BACKEND}
      - DATABASE_URL=${DB_URL}
      - MIGRATION_PATH=./src/migrations
      - BLOCK_WINDOW=1
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
  dev-wallet:
    profiles:
      - dev
    image: ghcr.io/onflow/fcl-dev-wallet:latest
    ports:
      - "8701:8701"
    environment:
      - FLOW_ACCESS_NODE=${ACCESS_API_BACKEND}
      - FLOW_ACCOUNT_ADDRESS=${FLOW_ADDRESS}
      - FLOW_ACCOUNT_KEY_ID=0
      - FLOW_ACCOUNT_PRIVATE_KEY=${FLOW_PRIVATE_KEY}
      - FLOW_ACCOUNT_PUBLIC_KEY=${FLOW_PUBLIC_KEY}
    depends_on:
      - emulator
  emulator:
    profiles:
      - dev
      - api
    image: gcr.io/flow-container-registry/emulator:v0.22.0
    ports:
      - "8080:8080"
      - "3569:3569"
    environment:
      - FLOW_SERVICEPRIVATEKEY=${FLOW_PRIVATE_KEY}
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
      - FLOW_VERBOSE=true
  db:
    profiles:
      - dev
      - testnet
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kittyitems
      - POSTGRES_USER=kittyuser
      - POSTGRES_PASSWORD=kittypassword
