name: Kitty Items Integration Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - gpavlov/update-github-actions-workflow
      - gpavlov/setup-cypress

jobs:
  jest:
    name: Kitty Items Integration Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16"]
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Flow CLI
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Root NPM Install
        run: npm i fs-jetpack chalk && npm i && npx lerna exec npm install

      - name: Run JS Tests
        run: npm i && npm run test
        working-directory: cadence/tests

      - name: Build & Run
        run: npm run dev:emulator & sleep 30

      - name: Deploy Contracts
        run: flow project deploy --network=emulator --update

  cypress:
      name: Kitty Items Cypress End to End tests
      timeout-minutes: 10
      runs-on: ubuntu-latest
      container: cypress/browsers:node16.14.2-slim-chrome103-ff102 #use arm64 arch on Apple M1 chips when running locally
      steps:
        - name: Install build dependencies (mostly for sqlite on ARM)
          run: apt-get update -y && apt-get install build-essential -y 

        - name: Install Flow CLI
          run: | 
            sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" &&
            echo "/root/.local/bin:/github/home/.local/bin" >> $GITHUB_PATH
            echo $HOME &&
            ls -l $HOME/.local/bin &&
            chmod a+r $HOME/.local/bin/flow &&
            ls -l $HOME/.local/bin &&
            $HOME/.local/bin/flow version
          # run: | 
          #   sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" &&
          #   echo "/root/.local/bin:/github/home/.local/bin" >> $GITHUB_PATH &&
          #   echo $HOME &&
          #   ls -l $HOME/.local/bin &&
          #   chmod a+r $HOME/.local/bin/flow &&
          #   ls -l $HOME/.local/bin &&
          #   $HOME/.local/bin/flow version

        - name: Checkout
          uses: actions/checkout@v3
        
        - name: chmod subdirs to bypass lerna exec access permission issues
          run: |
            pwd &&
            ls -l && 
            chmod -R 777 api &&
            chmod -R 777 web &&
            chmod -R 777 cadence/tests &&
            ls -l 

        - name: Install dependencies
          run: npm i && cd web && npm i && cat package-lock.json | grep swc

        - name: Start server
          run: npm run dev:emulator & npm i wait-on && npx wait-on http://localhost:3001

        - name: Cypress run
          uses: cypress-io/github-action@v4
          with:
            # start: npm run dev:emulator
            wait-on: http://localhost:3001

        - name: Print logs
          if: always()
          run: npx pm2 logs    

        - uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: cypress-screenshots
            path: cypress/screenshots
        # Test run video was always captured, so this action uses "always()" condition
        - uses: actions/upload-artifact@v2
          if: always()
          with:
            name: cypress-videos
            path: cypress/videos

  #     - name: Save build folder
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: build
  #         if-no-files-found: error
  #         path: build