name: Kitty Items Integration Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - gpavlov/update-github-actions-workflow

jobs:
  vm-job:
    name: Kitty Items Integration Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16"]
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Flow CLI
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Root NPM Install
        run: npm i fs-jetpack chalk && npm i && npx lerna exec npm install

      - name: Run JS Tests
        run: npm i && npm run test
        working-directory: cadence/tests

      - name: Build & Run
        run: npm run dev:emulator & sleep 30

      - name: Deploy Contracts
        run: flow project deploy --network=emulator --update

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm run test
          browser: chrome
          headless: true
          record: false
          config: baseUrl=http://localhost:3001,chromeWebSecurity=false

      - name: Stop Containers
        if: always()
        run: docker-compose down
